### ISSUE TITLE
Hs

### ISSUE THREAD

**Issue by Nefesar** [rine77/homeassistant-edupage#3]
Hallo erstmal ich freue mich das sie eine edupage Indikation geschrieben haben für Hs.
Installiert habe ich sie nur Leiter bekomme ich keine Können sie mir da weiter helfen?

**Comment by rine77** [comment]
Hallo!
Ich suche sowieso nach Testern, um die Benutzbarkeit zu erhöhen - würden Sie dabei helfen?
Gruß

**Comment by Nefesar** [comment]
Ja klar würde ich dabei helfen.--Gesendet mit der GMX Mail AppAm 25.10.24, 11:58 schrieb rine77 ***@***.***>:

Hallo!
Ich suche sowieso nach Testern, um die Benutzbarkeit zu erhöhen - würden Sie dabei helfen?
Gruß

**Comment by rine77** [comment]
Hallo @Nefesar ,

ich werde mich diese Woche mit ein paar Themen dazu befassen und mich direkt melden.

Beste Grüße

**Comment by Nefesar** [comment]
Gut danke ich freue mich von dir zu hören.Schönes Wochenende wünsche ich --Gesendet mit der GMX Mail AppAm 26.10.24, 08:02 schrieb rine77 ***@***.***>:

Hallo @Nefesar ,
ich werde mich diese Woche mit ein paar Themen dazu befassen und mich direkt melden.
Beste Grüße

**Comment by Nefesar** [comment]
Hallo ich habe immer noch das Problem das kleine Entitäten angezeigt werden. In den logs gibt es aber auch keine Fehlermeldung?Message ID: ***@***.***>Ich habe mich mit meinem Login Name und den Passwort angemeldet die Schulseite währe diesehttps://rs-steinbach-hallenberg.edupage.org/user/?c2fa=1Und Eingeben haben rs-steinbach-hallenbergDas dürfte soweit richtig sein Oder?Mit freundlichen Grüßen Sven Nothnagel

**Comment by rine77** [comment]
bei der Schulseite darfst du nur "rs-steinbach-hallenberg" eingeben - nicht den Teil mit edupage. Also nur die Subdomain.
Hilft das?

**Comment by Nefesar** [comment]
Ja das habe ich. Es kommen dann aber keine Entitäten.--Gesendet mit der GMX Mail AppAm 03.11.24, 10:39 schrieb rine77 ***@***.***>:

bei der Schulseite darfst du nur "rs-steinbach-hallenberg" eingeben - nicht den Teil mit edupage. Also nur die Subdomain.
Hilft das?

**Comment by Nefesar** [comment]
Ja Fächer und der Vertretungsplan, Note stellt man uns hier nicht zur Verfügung.--Gesendet mit der GMX Mail AppAm 03.11.24, 10:50 schrieb rine77 ***@***.***>:

Wenn du auf der Seite mit dem Browser dich einloggst, dann sind aber schon Noten und Unterrichtsfächer vorhanden?

**Comment by rine77** [comment]
Ok, das erklärt es. 
Die Liste der Fächer wird aus den vorhandenen Noten generiert. Keine Noten, keine Fächer -> keine Entities.
Das könnte ich mir aber sehr gern mal ansehen und umbauen. 
Welche Sensoren würden aus deiner Sicht noch Sinn machen? Da würde ich dich bitten, einen Feature-Request zu erstellen (einfach bei Issues open Template Feature wählen)

**Comment by Nefesar** [comment]
Ich denke der Vertretungsplan und Hausaufgaben sind wichtig.--Gesendet mit der GMX Mail AppAm 03.11.24, 11:06 schrieb rine77 ***@***.***>:

Ok, das erklärt es.
Die Liste der Fächer wird aus den vorhandenen Noten generiert. Keine Noten, keine Fächer -> keine Entities.
Das könnte ich mir aber sehr gern mal ansehen und umbauen.
Welche Sensoren würden aus deiner Sicht noch Sinn machen? Da würde ich dich bitten, einen Feature-Request zu erstellen (einfach bei Issues open Template Feature wählen)

**Comment by rine77** [comment]
ich schließe das mal hier weil #7
