### ISSUE TITLE
make it available in HACS 

### ISSUE THREAD

**Issue by rine77** [rine77/homeassistant-edupage#4]
**Is your feature request related to a problem? Please describe.**
It would make installation much easier and raises useability.

**Describe the solution you'd like**
I want the integration to be installable via HACS.

**Describe alternatives you've considered**
Manual installation sucks a bit.

**Additional context**
-

**Comment by Nefesar** [comment]
Hallo, sie lässt sich über Hacs nicht mehr Installieren im Anhang ist ein Screenshot.--Gesendet mit der GMX Mail AppAm 28.10.24, 08:00 schrieb rine77 ***@***.***>:

Is your feature request related to a problem? Please describe.
It would make installation much easier and raises useability.
Describe the solution you'd like
I want the integration to be installable via HACS.
Describe alternatives you've considered
Manual installation sucks a bit.
Additional context

**Comment by rine77** [comment]
this shouldnt be a great problem, I try to implement soon[TM]
